name: "emsdk"
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.24
          actions-cache-folder: "emsdk-cache"

      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
