name: "emsdk"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: mymindstorm/setup-emsdk@v11
        with:
          actions-cache-folder: "emsdk-cache"

      - name: Verify
        run: emcc -v
