name: "emsdk"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.24
          actions-cache-folder: "emsdk-cache"

      - name: Verify
        run: emcc -v
